require 'happymapper'

require_relative './timetable/Instructor.rb'
require_relative './timetable/Part.rb'
require_relative './timetable/Course.rb'
require_relative './timetable/Lesson.rb'
require_relative './timetable/DoubleClass.rb'
require_relative './timetable/WeekdayTable.rb'
require_relative './timetable/TimeTable.rb'
require_relative './timetable/CourseInfo.rb'
require_relative './timetable/CourseList.rb'
require_relative './timetable/Person.rb'
require_relative './timetable/Staff.rb'
